const _ENV_ = {
  SYNC_DB: true,
  LOG_DB: true,
  MONITOR: true,
  MONITOR_USER: 'test',
  CACHE_DB: false,
  LOG_LEVEL: 'debug',
  LOG_JSON: false,
  MONITOR_PASSWORD: 'test',
  LOG_OUTPUT: 'dev',
  LOG_TIMESTAMP: true,
  LOG_COLORIZE: true,
  MONITOR_ROUTE: '.monitor',
  SESSION_SECRET: '47e5394b64d149979f3b32',
  FALLBACK_SALT: 'zazaza',
  BASE_URL: 'http://127.0.0.1:3010',
  DATABASE_HOST: '127.0.0.1',
  DATABASE_USER: 'postgres',
  DATABASE_PASSWORD: 'JbJ1K3H2fKG65j6h6J4H56GJH',
  DATABASE_NAME: 'admin_powerpiper',
  DATABASE_PORT: 5432,
  API_URL: 'http://127.0.0.1:8010',
  API_PORT: 8010,
  FROM_EMAIL_ADDRESS: 'info@powerpiper.com',
  EMAIL_SERVER: 'smtp.elasticemail.com',
  EMAIL_PORT: 2525,
  EMAIL_USERNAME: 'placeholder',
  EMAIL_PASSWORD: 'placeholder',
  EMAIL_SECURE: true,
  ROUTE_PREFIX: '/api/1.0',
  CRYPT_KEY: 'HjkyhkkuyttyuUKYU' // use utils/crypto.generateKey
}

export default _ENV_
